//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a38
    {
        public int OBJECTID { get; set; }
        public string LOCATED_AREA { get; set; }
        public string REPER_NO { get; set; }
        public string WELL_TYPE { get; set; }
        public string ASSIGMENT { get; set; }
        public Nullable<decimal> PRODUCTIVITY { get; set; }
        public string SIB { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public string ACTIVITY { get; set; }
        public Nullable<decimal> IRRIGATED_AREA { get; set; }
        public string PROPERTY { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public Nullable<decimal> DEPTH { get; set; }
        public Nullable<decimal> NUMBER_ { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public long SDE_STATE_ID { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
