//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a39
    {
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public string SERVED_AREA { get; set; }
        public string DEVICE_SUM { get; set; }
        public string WATER_PIPE { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public long SDE_STATE_ID { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
