//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a70
    {
        public int OBJECTID { get; set; }
        public string USERNAME { get; set; }
        public string PAASWORD { get; set; }
        public long SDE_STATE_ID { get; set; }
    }
}
