//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BUILDING
    {
        public int OBJECTID { get; set; }
        public Nullable<int> ID { get; set; }

        [Display(Name = "Adı")]
        public string NAME { get; set; }

        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATIO { get; set; }

        [Display(Name = "Yerləşdiyi Ərazi")]
        public string REGION { get; set; }
        public string ACTION { get; set; }

        [Display(Name = "Təyinatı")]
        public string ASSIGMENT { get; set; }
        public string PROTECTING { get; set; }

        [Display(Name = "Ümumi sahə")]
        public Nullable<decimal> TOTAL_AREA { get; set; }

        [Display(Name = "Texniki vəziyyəti")]
        public string TECHNICAL_ { get; set; }
        public string USING_MODE { get; set; }

        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_T { get; set; }

        [Display(Name = "Mülkiyyətçi")]
        public string PROPERTY { get; set; }

        [Display(Name = "Tikili altı sahə")]
        public string SERVICE_AR { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
