//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHANNELS_3
    {
        public int OBJECTID { get; set; }
        [Display(Name = "Tipi")]
        public string TYPE { get; set; }
        [Display(Name = "Ad")]
        public string NAME { get; set; }
        [Display(Name = "Təyinatı")]
        public string ASSIGMENT { get; set; }
        [Display(Name = "Su buraxma qabiliyyəti")]
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }
        [Display(Name = "Xidmət etdiyi sahə")]
        public string SERVED_AREA { get; set; }

        public string ACTIVITY { get; set; }
        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }
        [Display(Name = "Mülkiyyətçisi")]
        public string PROPERTY { get; set; }
        [Display(Name = "Texniki vəziyyəti")]
        public string TECHNICAL_CONDITION { get; set; }

        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        [Display(Name = "Yerləşdiyi ərazi")]
        public string SERVERD_REGION { get; set; }

        public string KIND { get; set; }
        [Display(Name = "Üzərindəki qurğuların sayı")]
        public Nullable<decimal> DEVICE_SUM { get; set; }
        [Display(Name = "Su götürmə mənbəyi")]
        public string SOURCE { get; set; }
        [Display(Name = "Uzunluğu")]
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        public string EMPLOYEE { get; set; }
        public string COVER_TYPE { get; set; }
        [Display(Name = "Xidmət etdiyi SİB-lərin adı")]
        public string SIBS { get; set; }
        public string CHANNEL_ID { get; set; }
        public Nullable<short> ID_CHANNEL { get; set; }
        public string RESID_IDS { get; set; }
        public Nullable<decimal> GIS_LENGTH { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> SERVED_AREAHA { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
