//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DEVICE
    {
        public int OBJECTID { get; set; }

        [Display(Name = "Adı")]
        public string NAME { get; set; }

        public string EMPLOYEE { get; set; }
        public string CHANNEL_ID { get; set; }
        public Nullable<short> ID_CHANNEL { get; set; }

        [Display(Name = "Yerləşdiyi Ərazi")]
        public string LOCATED_NETWORK { get; set; }

        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }

        [Display(Name = "Tipi")]
        public string NETWORK_TYPE { get; set; }
        public Nullable<int> ACTIVITY { get; set; }

        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }

        [Display(Name = "Mülkiyyətçi")]
        public string PROPERTY { get; set; }

        [Display(Name = " Texniki vəziyyəti")]
        public string TECHNICAL_CONDITION { get; set; }

        [Display(Name = "Su buraxma qabiliyyəti")]
        public string WATER_CAPABILITY { get; set; }

        [Display(Name = "Xidmət etdiyi sahə")]
        public string SERVED_AREA { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
