//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DRENAJ_3
    {
        public int OBJECTID { get; set; }
        [Display(Name = "Tipi")]
        public string KIND { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        [Display(Name = "Xidmət etdiyi drenləşdirilmiş sahə")]
        public Nullable<decimal> SERVED_AREA { get; set; }
        [Display(Name = "Yerləşdiyi Ərazi")]
        public string PASSING_AREAS { get; set; }
        [Display(Name = "Texniki vəziyyəti")]
        public string TECHNICAL_CONDITION { get; set; }
        [Display(Name = "Üzərindəki qurğuların sayı")]
        public Nullable<decimal> DEVICE_SUM { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }
        [Display(Name = "Mülkiyyətçisi")]
        public string PROPERTY { get; set; }
        [Display(Name = "Uzunluğu")]
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }
        public string ACTIVITY { get; set; }
        [Display(Name = "Adı")]
        public string NAME { get; set; }
        [Display(Name = "Təyinatı")]
        public string ASSIGMENT { get; set; }
        [Display(Name = "Kollektorun normal və maksimum su sərfləri")]
        public string WATER_CONSUPTION { get; set; }
        [Display(Name = "Drenaj Sularının Qəbuledicisi")]
        public string DRENAJ_RECIEVER { get; set; }
        [Display(Name = "Coğrafi uzunluğu")]
        public Nullable<decimal> GISLENGTH { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
