//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MelogisEntities : DbContext
    {
        public MelogisEntities()
            : base("name=MelogisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a38> a38 { get; set; }
        public virtual DbSet<a39> a39 { get; set; }
        public virtual DbSet<a40> a40 { get; set; }
        public virtual DbSet<a41> a41 { get; set; }
        public virtual DbSet<a42> a42 { get; set; }
        public virtual DbSet<a43> a43 { get; set; }
        public virtual DbSet<a44> a44 { get; set; }
        public virtual DbSet<a45> a45 { get; set; }
        public virtual DbSet<a46> a46 { get; set; }
        public virtual DbSet<a47> a47 { get; set; }
        public virtual DbSet<a48> a48 { get; set; }
        public virtual DbSet<a49> a49 { get; set; }
        public virtual DbSet<a50> a50 { get; set; }
        public virtual DbSet<a51> a51 { get; set; }
        public virtual DbSet<a52> a52 { get; set; }
        public virtual DbSet<a53> a53 { get; set; }
        public virtual DbSet<a54> a54 { get; set; }
        public virtual DbSet<a55> a55 { get; set; }
        public virtual DbSet<a56> a56 { get; set; }
        public virtual DbSet<a57> a57 { get; set; }
        public virtual DbSet<a58> a58 { get; set; }
        public virtual DbSet<a59> a59 { get; set; }
        public virtual DbSet<a60> a60 { get; set; }
        public virtual DbSet<a61> a61 { get; set; }
        public virtual DbSet<a62> a62 { get; set; }
        public virtual DbSet<a63> a63 { get; set; }
        public virtual DbSet<a64> a64 { get; set; }
        public virtual DbSet<a65> a65 { get; set; }
        public virtual DbSet<a66> a66 { get; set; }
        public virtual DbSet<a67> a67 { get; set; }
        public virtual DbSet<a68> a68 { get; set; }
        public virtual DbSet<a69> a69 { get; set; }
        public virtual DbSet<a70> a70 { get; set; }
        public virtual DbSet<ARTEZIAN_WELL> ARTEZIAN_WELL { get; set; }
        public virtual DbSet<BUILDING> BUILDINGS { get; set; }
        public virtual DbSet<CHANNEL> CHANNELS { get; set; }
        public virtual DbSet<CHANNELS_1> CHANNELS_1 { get; set; }
        public virtual DbSet<CHANNELS_2> CHANNELS_2 { get; set; }
        public virtual DbSet<CHANNELS_3> CHANNELS_3 { get; set; }
        public virtual DbSet<CHANNELS_D> CHANNELS_D { get; set; }
        public virtual DbSet<CHANNELS_H> CHANNELS_H { get; set; }
        public virtual DbSet<CHANNELS_M> CHANNELS_M { get; set; }
        public virtual DbSet<D38> D38 { get; set; }
        public virtual DbSet<D39> D39 { get; set; }
        public virtual DbSet<D40> D40 { get; set; }
        public virtual DbSet<D41> D41 { get; set; }
        public virtual DbSet<D42> D42 { get; set; }
        public virtual DbSet<D43> D43 { get; set; }
        public virtual DbSet<D44> D44 { get; set; }
        public virtual DbSet<D45> D45 { get; set; }
        public virtual DbSet<D46> D46 { get; set; }
        public virtual DbSet<D47> D47 { get; set; }
        public virtual DbSet<D48> D48 { get; set; }
        public virtual DbSet<D49> D49 { get; set; }
        public virtual DbSet<D50> D50 { get; set; }
        public virtual DbSet<D51> D51 { get; set; }
        public virtual DbSet<D52> D52 { get; set; }
        public virtual DbSet<D53> D53 { get; set; }
        public virtual DbSet<D54> D54 { get; set; }
        public virtual DbSet<D55> D55 { get; set; }
        public virtual DbSet<D56> D56 { get; set; }
        public virtual DbSet<D57> D57 { get; set; }
        public virtual DbSet<D58> D58 { get; set; }
        public virtual DbSet<D59> D59 { get; set; }
        public virtual DbSet<D60> D60 { get; set; }
        public virtual DbSet<D61> D61 { get; set; }
        public virtual DbSet<D62> D62 { get; set; }
        public virtual DbSet<D63> D63 { get; set; }
        public virtual DbSet<D64> D64 { get; set; }
        public virtual DbSet<D65> D65 { get; set; }
        public virtual DbSet<D66> D66 { get; set; }
        public virtual DbSet<D67> D67 { get; set; }
        public virtual DbSet<D68> D68 { get; set; }
        public virtual DbSet<D69> D69 { get; set; }
        public virtual DbSet<D70> D70 { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DbSet<DEVICE> DEVICEs { get; set; }
        public virtual DbSet<DRENAJ> DRENAJs { get; set; }
        public virtual DbSet<DRENAJ_1> DRENAJ_1 { get; set; }
        public virtual DbSet<DRENAJ_2> DRENAJ_2 { get; set; }
        public virtual DbSet<DRENAJ_3> DRENAJ_3 { get; set; }
        public virtual DbSet<DRENAJ_D> DRENAJ_D { get; set; }
        public virtual DbSet<DRENAJ_H> DRENAJ_H { get; set; }
        public virtual DbSet<DRENAJ_M> DRENAJ_M { get; set; }
        public virtual DbSet<EXPLOITATION_ROAD> EXPLOITATION_ROAD { get; set; }
        public virtual DbSet<GDB_ITEMRELATIONSHIPS> GDB_ITEMRELATIONSHIPS { get; set; }
        public virtual DbSet<GDB_ITEMS> GDB_ITEMS { get; set; }
        public virtual DbSet<i2> i2 { get; set; }
        public virtual DbSet<i3> i3 { get; set; }
        public virtual DbSet<i38> i38 { get; set; }
        public virtual DbSet<i39> i39 { get; set; }
        public virtual DbSet<i4> i4 { get; set; }
        public virtual DbSet<i40> i40 { get; set; }
        public virtual DbSet<i41> i41 { get; set; }
        public virtual DbSet<i42> i42 { get; set; }
        public virtual DbSet<i43> i43 { get; set; }
        public virtual DbSet<i44> i44 { get; set; }
        public virtual DbSet<i45> i45 { get; set; }
        public virtual DbSet<i46> i46 { get; set; }
        public virtual DbSet<i47> i47 { get; set; }
        public virtual DbSet<i48> i48 { get; set; }
        public virtual DbSet<i49> i49 { get; set; }
        public virtual DbSet<i5> i5 { get; set; }
        public virtual DbSet<i50> i50 { get; set; }
        public virtual DbSet<i51> i51 { get; set; }
        public virtual DbSet<i52> i52 { get; set; }
        public virtual DbSet<i53> i53 { get; set; }
        public virtual DbSet<i54> i54 { get; set; }
        public virtual DbSet<i55> i55 { get; set; }
        public virtual DbSet<i56> i56 { get; set; }
        public virtual DbSet<i57> i57 { get; set; }
        public virtual DbSet<i58> i58 { get; set; }
        public virtual DbSet<i59> i59 { get; set; }
        public virtual DbSet<i6> i6 { get; set; }
        public virtual DbSet<i60> i60 { get; set; }
        public virtual DbSet<i61> i61 { get; set; }
        public virtual DbSet<i62> i62 { get; set; }
        public virtual DbSet<i63> i63 { get; set; }
        public virtual DbSet<i64> i64 { get; set; }
        public virtual DbSet<i65> i65 { get; set; }
        public virtual DbSet<i66> i66 { get; set; }
        public virtual DbSet<i67> i67 { get; set; }
        public virtual DbSet<i68> i68 { get; set; }
        public virtual DbSet<i69> i69 { get; set; }
        public virtual DbSet<i70> i70 { get; set; }
        public virtual DbSet<MELOREGION> MELOREGIONS { get; set; }
        public virtual DbSet<MUNICIPALITy> MUNICIPALITIES { get; set; }
        public virtual DbSet<PUMPSTATION> PUMPSTATIONs { get; set; }
        public virtual DbSet<REGION_TYPE> REGION_TYPE { get; set; }
        public virtual DbSet<REGION> REGIONS { get; set; }
        public virtual DbSet<RESIDENTIAL_AREA> RESIDENTIAL_AREA { get; set; }
        public virtual DbSet<RESIDENTIALAREA> RESIDENTIALAREAs { get; set; }
        public virtual DbSet<RIVERBAND> RIVERBANDs { get; set; }
        public virtual DbSet<SDE_archives> SDE_archives { get; set; }
        public virtual DbSet<SDE_column_registry> SDE_column_registry { get; set; }
        public virtual DbSet<SDE_dbtune> SDE_dbtune { get; set; }
        public virtual DbSet<SDE_geometry_columns> SDE_geometry_columns { get; set; }
        public virtual DbSet<SDE_GEOMETRY1> SDE_GEOMETRY1 { get; set; }
        public virtual DbSet<SDE_GEOMETRY33> SDE_GEOMETRY33 { get; set; }
        public virtual DbSet<SDE_GEOMETRY34> SDE_GEOMETRY34 { get; set; }
        public virtual DbSet<SDE_GEOMETRY35> SDE_GEOMETRY35 { get; set; }
        public virtual DbSet<SDE_GEOMETRY36> SDE_GEOMETRY36 { get; set; }
        public virtual DbSet<SDE_GEOMETRY37> SDE_GEOMETRY37 { get; set; }
        public virtual DbSet<SDE_GEOMETRY38> SDE_GEOMETRY38 { get; set; }
        public virtual DbSet<SDE_GEOMETRY39> SDE_GEOMETRY39 { get; set; }
        public virtual DbSet<SDE_GEOMETRY40> SDE_GEOMETRY40 { get; set; }
        public virtual DbSet<SDE_GEOMETRY41> SDE_GEOMETRY41 { get; set; }
        public virtual DbSet<SDE_GEOMETRY42> SDE_GEOMETRY42 { get; set; }
        public virtual DbSet<SDE_GEOMETRY43> SDE_GEOMETRY43 { get; set; }
        public virtual DbSet<SDE_GEOMETRY44> SDE_GEOMETRY44 { get; set; }
        public virtual DbSet<SDE_GEOMETRY45> SDE_GEOMETRY45 { get; set; }
        public virtual DbSet<SDE_GEOMETRY46> SDE_GEOMETRY46 { get; set; }
        public virtual DbSet<SDE_GEOMETRY47> SDE_GEOMETRY47 { get; set; }
        public virtual DbSet<SDE_GEOMETRY48> SDE_GEOMETRY48 { get; set; }
        public virtual DbSet<SDE_GEOMETRY49> SDE_GEOMETRY49 { get; set; }
        public virtual DbSet<SDE_GEOMETRY50> SDE_GEOMETRY50 { get; set; }
        public virtual DbSet<SDE_GEOMETRY51> SDE_GEOMETRY51 { get; set; }
        public virtual DbSet<SDE_GEOMETRY52> SDE_GEOMETRY52 { get; set; }
        public virtual DbSet<SDE_GEOMETRY53> SDE_GEOMETRY53 { get; set; }
        public virtual DbSet<SDE_GEOMETRY54> SDE_GEOMETRY54 { get; set; }
        public virtual DbSet<SDE_GEOMETRY55> SDE_GEOMETRY55 { get; set; }
        public virtual DbSet<SDE_GEOMETRY56> SDE_GEOMETRY56 { get; set; }
        public virtual DbSet<SDE_GEOMETRY57> SDE_GEOMETRY57 { get; set; }
        public virtual DbSet<SDE_GEOMETRY58> SDE_GEOMETRY58 { get; set; }
        public virtual DbSet<SDE_GEOMETRY59> SDE_GEOMETRY59 { get; set; }
        public virtual DbSet<SDE_GEOMETRY60> SDE_GEOMETRY60 { get; set; }
        public virtual DbSet<SDE_layer_locks> SDE_layer_locks { get; set; }
        public virtual DbSet<SDE_layer_stats> SDE_layer_stats { get; set; }
        public virtual DbSet<SDE_layers> SDE_layers { get; set; }
        public virtual DbSet<SDE_lineages_modified> SDE_lineages_modified { get; set; }
        public virtual DbSet<SDE_locators> SDE_locators { get; set; }
        public virtual DbSet<SDE_logfile_pool> SDE_logfile_pool { get; set; }
        public virtual DbSet<SDE_metadata> SDE_metadata { get; set; }
        public virtual DbSet<SDE_object_ids> SDE_object_ids { get; set; }
        public virtual DbSet<SDE_object_locks> SDE_object_locks { get; set; }
        public virtual DbSet<SDE_process_information> SDE_process_information { get; set; }
        public virtual DbSet<SDE_raster_columns> SDE_raster_columns { get; set; }
        public virtual DbSet<SDE_server_config> SDE_server_config { get; set; }
        public virtual DbSet<SDE_spatial_references> SDE_spatial_references { get; set; }
        public virtual DbSet<SDE_state_lineages> SDE_state_lineages { get; set; }
        public virtual DbSet<SDE_state_locks> SDE_state_locks { get; set; }
        public virtual DbSet<SDE_states> SDE_states { get; set; }
        public virtual DbSet<SDE_table_locks> SDE_table_locks { get; set; }
        public virtual DbSet<SDE_table_registry> SDE_table_registry { get; set; }
        public virtual DbSet<SDE_tables_modified> SDE_tables_modified { get; set; }
        public virtual DbSet<SDE_version> SDE_version { get; set; }
        public virtual DbSet<SDE_versions> SDE_versions { get; set; }
        public virtual DbSet<SDE_xml_columns> SDE_xml_columns { get; set; }
        public virtual DbSet<SDE_xml_index_tags> SDE_xml_index_tags { get; set; }
        public virtual DbSet<SDE_xml_indexes> SDE_xml_indexes { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<USERADMIN> USERADMINs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WELL> WELLs { get; set; }
        public virtual DbSet<WINTERPASTURE> WINTERPASTURES { get; set; }
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<GDB_ITEMRELATIONSHIPTYPES> GDB_ITEMRELATIONSHIPTYPES { get; set; }
        public virtual DbSet<GDB_ITEMTYPES> GDB_ITEMTYPES { get; set; }
        public virtual DbSet<GDB_REPLICALOG> GDB_REPLICALOG { get; set; }
        public virtual DbSet<GDB_TABLES_LAST_MODIFIED> GDB_TABLES_LAST_MODIFIED { get; set; }
    }
}
