//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> GID { get; set; }
        public Nullable<decimal> F__GID { get; set; }
        public string NAME_AZ { get; set; }
        public string CODE_TYPE { get; set; }
        public string NAME_ENG { get; set; }
        public string REGION_TYP { get; set; }
        public string NAME { get; set; }
        public Nullable<short> REGION_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
    }
}
