//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RIVERBAND
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        [Display(Name = "Adı")]
        public string NAME { get; set; }
        [Display(Name = "Hündürlüyü")]
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        [Display(Name = "İstismara verildiyi tarix")]
        public string EXPLONATION_DATE { get; set; }
        [Display(Name = "Bəndin Növü")]
        public string GENERAL_TYPE { get; set; }
        [Display(Name = "Texniki vəziyyəti")]
        public string TECHNICAL_CONDITION { get; set; }
        [Display(Name = "Mülkiyyət növü")]
        public string PROPERTY_TYPE { get; set; }
        [Display(Name = "Bəndin Uzunluğu")]
        public string PROPERTY { get; set; }
        [Display(Name = "Təyinatı")]
        public string ASSIGMENT { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
