//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERADMIN
    {
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public Nullable<int> REGION_TYPE_ID { get; set; }
        public int OBJECTID { get; set; }
    
        public virtual MELOREGION MELOREGION { get; set; }
        public virtual REGION_TYPE REGION_TYPE { get; set; }
    }
}
