//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WELL
    {
        public int OBJECTID { get; set; }
        [Display(Name = "Adı")]
        public string NAME { get; set; }

        public string LOCATION { get; set; }
        public string WELL_TYPE { get; set; }
        public string ASSIGMENT { get; set; }
        public string SIB { get; set; }
        public string EXPLONATION_DATE { get; set; }
        public Nullable<short> ACTIVITY { get; set; }
        public string IRRIGATED_AREA { get; set; }
        public string TECHNICAL_CONDITION { get; set; }
        public string DEPTH { get; set; }
        public string PROPERTY_TYPE { get; set; }
        public string PROPERTY { get; set; }
        public string NUMBER_ { get; set; }
        public string PRODUCTIVITY { get; set; }
        public string SECURITY_TYPE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public Nullable<int> Municipality_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> USER_ADMIN_ID { get; set; }
    }
}
